FROM debian
LABEL maintainer 'Rafael Coutinho'

#Cria um argumento com o valor padrao files
ARG S3_BUCKET_ARG=files

#Aplica o argumento para uma variavel de ambiente 
ENV S3_BUCKET_ENV=${S3_BUCKET_ARG}


